# Generated by Django 4.2.4 on 2023-10-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stexpensecategory',
            name='latin_name',
        ),
        migrations.RemoveField(
            model_name='stexpensesubcategory',
            name='latin_name',
        ),
    ]
