# Generated by Django 4.2.4 on 2023-08-25 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stquest',
            old_name='photomagnets_not_promo_quantity',
            new_name='photomagnets',
        ),
        migrations.RemoveField(
            model_name='stquest',
            name='photomagnets_not_promo_sum',
        ),
        migrations.RemoveField(
            model_name='stquest',
            name='photomagnets_promo_quantity',
        ),
        migrations.RemoveField(
            model_name='stquest',
            name='photomagnets_promo_sum',
        ),
        migrations.AlterField(
            model_name='stquest',
            name='room_employee_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_employee_stquest', to=settings.AUTH_USER_MODEL),
        ),
    ]
