# Generated by Django 4.2.4 on 2023-09-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='rate',
            new_name='actor_rate',
        ),
        migrations.AddField(
            model_name='quest',
            name='administrator_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='animator_rate',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
