# Generated by Django 4.2.4 on 2023-09-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_rate_quest_actor_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qincome',
            name='paid_cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qincome',
            name='paid_non_cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stexpense',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='stexpense',
            name='who_paid_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
