# Generated by Django 4.2.4 on 2023-08-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_photomagnets_not_promo_quantity_stquest_photomagnets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stquest',
            old_name='photomagnets',
            new_name='photomagnets_quantity',
        ),
        migrations.AddField(
            model_name='stquest',
            name='photomagnets_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
