# Generated by Django 4.2.4 on 2023-12-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_qsalary_quest_alter_qsalary_stquest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qvideo',
            name='is_package',
        ),
        migrations.AddField(
            model_name='qvideo',
            name='type',
            field=models.CharField(choices=[('package', 'пакет'), ('video_review', 'видео отзыв')], default='package', max_length=255),
        ),
    ]
