# Generated by Django 4.2.4 on 2023-08-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_photomagnets_stquest_photomagnets_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.quest')),
            ],
        ),
    ]
