# Generated by Django 4.2.4 on 2023-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_qincome_paid_cash_qincome_paid_non_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stexpense',
            name='who_paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
