# Generated by Django 4.2.4 on 2023-11-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stexpense_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='questversion',
            name='cost_weekdays_with_package',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questversion',
            name='cost_weekends_with_package',
            field=models.IntegerField(default=0),
        ),
    ]
