# Generated by Django 4.2.4 on 2023-10-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questversion_cost_weekdays_with_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stexpense',
            name='paid_from',
            field=models.CharField(blank=True, choices=[('work_card', 'рабочая карта'), ('own', 'свои'), ('cash_register', 'касса')], max_length=255, null=True),
        ),
    ]
