# Generated by Django 4.2.3 on 2023-08-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questform_expensesform_bonusespenaltiesform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_rate',
            field=models.IntegerField(verbose_name='Ставка квеста'),
        ),
    ]
