# Generated by Django 4.2.4 on 2023-10-16 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_stexpense_paid_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stexpense',
            name='paid_tax',
        ),
        migrations.RemoveField(
            model_name='stexpense',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='stexpense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stexpense',
            name='who_paid_amount',
        ),
        migrations.AddField(
            model_name='stexpense',
            name='description',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='stexpense',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employees_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stexpense',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stexpense',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
