# Generated by Django 4.2.4 on 2023-09-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_stexpense_who_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcashregister',
            name='stquest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stquest'),
        ),
    ]
