# Generated by Django 4.2.4 on 2023-12-10 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stquest_administrator_half'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stquest',
            name='administrator_half',
        ),
        migrations.AddField(
            model_name='stquest',
            name='administrators_half',
            field=models.ManyToManyField(blank=True, related_name='administrators_half_stquest', to=settings.AUTH_USER_MODEL),
        ),
    ]
