# Generated by Django 4.2.4 on 2023-10-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_stexpense_paid_tax_remove_stexpense_quest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qsalary',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
