# Generated by Django 4.2.4 on 2023-09-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_qcashregister_stquest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcashregister',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
