# Generated by Django 4.2.4 on 2023-12-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_stquest_administrator_half_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.CharField(blank=True, choices=[('sberbank', 'сбербанк'), ('tinkoff', 'тинькофф'), ('alfabank', 'альфа-банк')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_for_transfer',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='Номер телефона для перевода'),
        ),
    ]
