# Generated by Django 4.2.3 on 2023-08-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_expensescategory_alter_income_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='expensescategory',
            name='sub',
            field=models.ManyToManyField(blank=True, to='main.expensessubcategory'),
        ),
    ]
