# Generated by Django 4.2.4 on 2023-10-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_qsalary_is_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qsalary',
            name='is_show',
        ),
        migrations.AddField(
            model_name='qsalary',
            name='st_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stexpense'),
        ),
    ]
