# Generated by Django 4.2.3 on 2023-08-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_expensessubcategory_expensescategory_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='key',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='key',
            new_name='object',
        ),
    ]
