# Generated by Django 4.2.3 on 2023-08-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_key_expenses_object_rename_key_salary_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questform',
            old_name='room_name',
            new_name='room_employee_name',
        ),
    ]
