# Generated by Django 4.2.4 on 2023-09-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_qcashregister_stexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensefromtheir',
            old_name='who_paid',
            new_name='paid_from_who',
        ),
        migrations.AddField(
            model_name='expensefromtheir',
            name='paid_from',
            field=models.CharField(choices=[('work_card', 'Рабочая карта'), ('their', 'Свои'), ('cash_register', 'Касса')], default='work_card', max_length=255),
        ),
    ]
