# Generated by Django 4.2.4 on 2023-10-16 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_qsalary_is_show_qsalary_st_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='stexpense',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stexpense_quest', to='main.quest'),
        ),
        migrations.AddField(
            model_name='stexpense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stexpense_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
