# Generated by Django 4.2.4 on 2023-12-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_expensefromtheir_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stquest',
            name='cashless_payment_after',
        ),
        migrations.AlterField(
            model_name='expensefromtheir',
            name='bank',
            field=models.CharField(blank=True, choices=[('sberbank', 'сбербанк'), ('tinkoff', 'тинькофф'), ('alfabank', 'альфа-банк'), ('vtb', 'втб')], max_length=255, null=True),
        ),
    ]
