# Generated by Django 4.2.3 on 2023-08-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_room_name_questform_room_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional1Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
