# Generated by Django 4.2.4 on 2023-09-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_who_paid_expensefromtheir_paid_from_who_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensefromtheir',
            old_name='paid_from_who',
            new_name='who_paid',
        ),
        migrations.RemoveField(
            model_name='expensefromtheir',
            name='paid_from',
        ),
        migrations.AddField(
            model_name='stexpense',
            name='paid_from',
            field=models.CharField(choices=[('work_card', 'Рабочая карта'), ('their', 'Свои'), ('cash_register', 'Касса')], default='work_card', max_length=255),
        ),
    ]
