# Generated by Django 4.2.4 on 2023-12-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_stquest_cashless_payment_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stquest',
            name='cashless_payment_after',
            field=models.IntegerField(default=0),
        ),
    ]
