# Generated by Django 4.2.4 on 2023-10-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_stquest_employee_with_staj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stquest',
            old_name='actor_second_actor',
            new_name='actor_or_second_actor_or_animator',
        ),
    ]
