# Generated by Django 4.2.4 on 2023-09-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_paid_from_who_expensefromtheir_who_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='animator_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
