# Generated by Django 4.2.4 on 2023-10-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_actor_second_actor_stquest_actor_or_second_actor_or_animator'),
    ]

    operations = [
        migrations.AddField(
            model_name='qincome',
            name='discount_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='qincome',
            name='discount_sum',
            field=models.IntegerField(default=0),
        ),
    ]
