# Generated by Django 4.2.4 on 2023-12-15 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_qincome_video_after'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stbonuspenalty',
            name='user',
        ),
        migrations.AddField(
            model_name='stbonuspenalty',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
