# Generated by Django 4.2.4 on 2023-09-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_quest_animator_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='duration_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
