# Generated by Django 4.2.3 on 2023-08-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_additional1form_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional1form',
            name='status',
            field=models.CharField(choices=[('error', 'Отклонена'), ('processing', 'В ожидании'), ('success', 'Одобрена')], default='processing', max_length=255, verbose_name='Статус'),
        ),
    ]
