# Generated by Django 4.2.4 on 2023-12-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_stbonuspenalty_user_stbonuspenalty_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quests_for_videos',
            field=models.ManyToManyField(to='main.quest', verbose_name='Квесты'),
        ),
    ]
