# Generated by Django 4.2.4 on 2023-09-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_quest_duration_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensefromtheir',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quest'),
        ),
        migrations.AddField(
            model_name='workcardexpense',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quest'),
        ),
    ]
