# Generated by Django 4.2.4 on 2023-10-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_qincome_discount_desc_qincome_discount_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qincome',
            name='discount_desc',
        ),
        migrations.RemoveField(
            model_name='qincome',
            name='discount_sum',
        ),
    ]
