# Generated by Django 4.2.4 on 2023-09-08 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_expensefromtheir_quest_workcardexpense_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='STBonusPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bonus', 'Бонус'), ('penalty', 'Штраф')], default='bonus', max_length=255)),
                ('quests', models.ManyToManyField(blank=True, to='main.quest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='stpenalty',
            name='quests',
        ),
        migrations.RemoveField(
            model_name='stpenalty',
            name='user',
        ),
        migrations.DeleteModel(
            name='STBonus',
        ),
        migrations.DeleteModel(
            name='STPenalty',
        ),
    ]
