# Generated by Django 4.2.4 on 2023-10-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_qincome_discount_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qincome',
            name='discount_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='qincome',
            name='discount_sum',
            field=models.IntegerField(default=0),
        ),
    ]
