# Generated by Django 4.2.4 on 2023-12-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user_quests_for_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensefromtheir',
            name='phone_number_for_transfer',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Номер телефона для перевода'),
        ),
    ]
