# Generated by Django 4.2.4 on 2023-09-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_stbonuspenalty_remove_stpenalty_quests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcashregister',
            old_name='stquest',
            new_name='quest',
        ),
    ]
