# Generated by Django 4.2.4 on 2023-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_qincome_discount_desc_qincome_discount_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='qincome',
            name='easy_work',
            field=models.IntegerField(default=0),
        ),
    ]
