# Generated by Django 4.2.4 on 2023-12-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_stquest_video_as_a_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quests_for_videos',
            field=models.ManyToManyField(blank=True, to='main.quest', verbose_name='Квесты'),
        ),
    ]
