# Generated by Django 4.2.4 on 2023-09-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_stquest_qcashregister_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcashregister',
            name='stquest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stquest'),
        ),
        migrations.AlterField(
            model_name='qcashregister',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quest'),
        ),
    ]
