# Generated by Django 4.2.4 on 2023-10-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_qincome_easy_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stexpense',
            name='quests',
        ),
    ]
