# Generated by Django 4.2.4 on 2023-09-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_qcashregister_stquest_alter_qcashregister_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensefromtheir',
            name='stexpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stexpense'),
        ),
        migrations.AddField(
            model_name='workcardexpense',
            name='stexpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stexpense'),
        ),
    ]
