# Generated by Django 4.2.4 on 2023-10-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_stexpense_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='stexpense',
            name='quests',
            field=models.ManyToManyField(blank=True, to='main.quest'),
        ),
    ]
