# Generated by Django 4.2.4 on 2023-10-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_stexpense_quests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stexpense',
            name='quests',
            field=models.ManyToManyField(blank=True, related_name='stexpense_quests', to='main.quest'),
        ),
    ]
