# Generated by Django 4.2.4 on 2024-03-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_correctnessofsalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctnessofsalary',
            name='stquest',
        ),
        migrations.AddField(
            model_name='correctnessofsalary',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.qsalary'),
        ),
    ]
