# Generated by Django 4.2.4 on 2024-03-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_qsalary_is_correct_delete_correctnessofsalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qsalary',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='qsalary',
            name='status',
            field=models.CharField(choices=[('correctly', 'верно'), ('incorrectly', 'не верно'), ('unknown', 'неизвестно')], default='unknown', max_length=255),
        ),
    ]
