# Generated by Django 4.2.4 on 2024-03-14 16:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_qsalary_is_correct_qsalary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stquest',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='STQuestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation', models.CharField(blank=True, choices=[('create', 'создание'), ('edit', 'редактирование'), ('delete', 'удаление')], max_length=255, null=True)),
                ('stquest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stquest')),
            ],
        ),
        migrations.CreateModel(
            name='STExpenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation', models.CharField(blank=True, choices=[('create', 'создание'), ('edit', 'редактирование'), ('delete', 'удаление')], max_length=255, null=True)),
                ('stexpense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stexpense')),
            ],
        ),
    ]
