# Generated by Django 4.2.4 on 2023-09-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_stexpense_paid_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='special_versions',
            field=models.ManyToManyField(blank=True, to='main.quest'),
        ),
        migrations.AddField(
            model_name='quest',
            name='versions',
            field=models.ManyToManyField(blank=True, to='main.questversion'),
        ),
    ]
