# Generated by Django 4.2.4 on 2023-09-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_questversion_quest_special_versions_quest_versions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='duration_minute',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='latin_name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='latin_name',
        ),
        migrations.RemoveField(
            model_name='stexpensecategory',
            name='latin_name',
        ),
        migrations.RemoveField(
            model_name='stexpensesubcategory',
            name='latin_name',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='main.role', verbose_name='Роли пользователя'),
        ),
    ]
