# Generated by Django 4.2.4 on 2024-03-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_stquest_created_date_stquesthistory_stexpensehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stexpensehistory',
            name='stexpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.stexpense'),
        ),
        migrations.AlterField(
            model_name='stquesthistory',
            name='stquest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.stquest'),
        ),
    ]
