# Generated by Django 4.2.4 on 2024-03-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_stexpensehistory_stexpense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stquesthistory',
            name='stquest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stquest'),
        ),
    ]
