# Generated by Django 4.2.4 on 2024-03-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_stquesthistory_stquest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stquest',
            name='created_date',
        ),
    ]
