# Generated by Django 4.2.4 on 2023-09-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='QVideo',
        ),
    ]
