# Generated by Django 4.2.4 on 2023-10-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_user_date_joined_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='duration',
            new_name='cost_weekdays',
        ),
        migrations.AddField(
            model_name='quest',
            name='cost_weekends',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='duration_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
