# Generated by Django 4.2.4 on 2023-10-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_duration_quest_cost_weekdays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stquest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
