# Generated by Django 4.2.4 on 2023-10-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stexpense',
            old_name='image',
            new_name='attachment',
        ),
    ]
