# Generated by Django 4.2.4 on 2023-10-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_image_stexpense_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stexpense',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
