# Generated by Django 4.2.4 on 2023-10-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_stexpense_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stquest',
            old_name='package',
            new_name='isPackage',
        ),
        migrations.RenameField(
            model_name='stquest',
            old_name='travel',
            new_name='isTravel',
        ),
    ]
