# Generated by Django 4.2.4 on 2023-10-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_package_stquest_ispackage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stquest',
            old_name='isPackage',
            new_name='is_package',
        ),
        migrations.RenameField(
            model_name='stquest',
            old_name='isTravel',
            new_name='is_video_review',
        ),
    ]
