# Generated by Django 4.2.4 on 2023-10-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_ispackage_stquest_is_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qincome',
            name='actor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qincome',
            name='game',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qincome',
            name='paid_cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qincome',
            name='paid_non_cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qincome',
            name='photomagnets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qincome',
            name='room',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qincome',
            name='video',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
