# Generated by Django 4.2.4 on 2023-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_qincome_actor_alter_qincome_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stquest',
            name='actor_second_actor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='add_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='birthday_congr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='cash_delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='cash_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='cashless_delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='cashless_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='discount_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='discount_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='easy_work',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='is_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='is_video_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='night_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='photomagnets_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='photomagnets_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='prepayment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='room_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='room_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stquest',
            name='video',
            field=models.IntegerField(default=0),
        ),
    ]
