# Generated by Django 4.2.4 on 2023-10-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_stquest_actor_second_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qvideo',
            name='is_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qvideo',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
