# Generated by Django 4.2.4 on 2023-10-10 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_qvideo_is_package_qvideo_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='stquest',
            name='employee_with_staj',
            field=models.ManyToManyField(blank=True, related_name='employee_with_staj_stquest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='quest_staj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_staf_user', to='main.quest'),
        ),
        migrations.AddField(
            model_name='user',
            name='range_staj_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='range_staj_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_user', to='main.quest'),
        ),
    ]
