# Generated by Django 4.2.4 on 2023-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_stquest_employee_with_staj_user_quest_staj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stquest',
            name='cash_delivery_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stquest',
            name='cash_payment_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stquest',
            name='cashless_delivery_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stquest',
            name='cashless_payment_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stquest',
            name='photomagnets_quantity_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stquest',
            name='video_after',
            field=models.IntegerField(default=0),
        ),
    ]
