# Generated by Django 4.2.4 on 2023-10-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_stquest_cash_delivery_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stquest',
            name='client_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
