# Generated by Django 4.2.4 on 2023-10-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_qvideo_stquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='questversion',
            name='cost_weekdays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questversion',
            name='cost_weekends',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
