# Generated by Django 4.2.4 on 2023-10-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_quest_cost_weekdays_with_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questversion',
            name='cost_weekdays_with_package',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questversion',
            name='cost_weekends_with_package',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
