# Generated by Django 4.2.4 on 2023-10-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_questversion_cost_weekdays_with_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questversion',
            name='cost_weekdays_with_package',
        ),
        migrations.RemoveField(
            model_name='questversion',
            name='cost_weekends_with_package',
        ),
    ]
