# Generated by Django 4.2.4 on 2023-10-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_qsalary_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qsalary',
            name='sub_category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
