# Generated by Django 4.2.4 on 2023-10-13 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_qsalary_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stexpense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stexpense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stexpense',
            name='paid_from',
            field=models.CharField(blank=True, choices=[('work_card', 'Рабочая карта'), ('their', 'Свои'), ('cash_register', 'Касса')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stexpense',
            name='who_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='who_paid_st_expense', to=settings.AUTH_USER_MODEL),
        ),
    ]
