# Generated by Django 4.2.4 on 2023-10-13 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_stexpense_user_alter_stexpense_paid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stexpense',
            name='stquest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stquest'),
        ),
    ]
