# Generated by Django 4.2.4 on 2023-10-13 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_stexpense_stquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='stexpense',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_stexpense', to='main.quest'),
        ),
    ]
