# Generated by Django 4.2.4 on 2023-10-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_stexpense_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='qincome',
            name='game_tooltip',
            field=models.CharField(default='', max_length=255),
        ),
    ]
